# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master", "code" ]
  pull_request:
    branches: [ "master", "code" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: TeamspeakStatsNew/TeamspeakStatsNew/package-lock.json
    - name: Install Dependencies
      run: |
        cd ./TeamspeakStatsNew/TeamspeakStatsNew
        npm ci
    - name: Build
      run: |
        cd ./TeamspeakStatsNew/TeamspeakStatsNew
        npm run build --if-present
    - name: Test
      run: |
        cd ./TeamspeakStatsNew/TeamspeakStatsNew
        npm run test:prod
    - name: Lint
      run: |
        cd ./TeamspeakStatsNew/TeamspeakStatsNew
        npm run lint
